// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
	"github.com/takkee/go-sample-api/domain"
	"github.com/takkee/go-sample-api/domain/service"
	"github.com/takkee/go-sample-api/infrastructure/api/handler"
	"github.com/takkee/go-sample-api/infrastructure/persistence/datastore"
	"github.com/takkee/go-sample-api/interface/controller"
	"github.com/takkee/go-sample-api/usecase"
)

// Injectors from injector.go:

func InitializeApp(conn *gorm.DB) handler.AppHandler {
	indexHandler := handler.NewIndexHandler()
	userRepository := datastore.NewUserRepository(conn)
	userActiveRepository := datastore.NewUserActiveRepository(conn)
	userService := service.NewUserService(userRepository, userActiveRepository)
	userDetailRepository := datastore.NewUserDetailRepository(conn)
	profileService := service.NewProfileService(userDetailRepository)
	userUseCase := usecase.NewUserUseCase(userService, profileService)
	userController := controller.NewUserController(userUseCase)
	userHandler := handler.NewUserHandler(userController)
	appHandler := handler.NewAppHandler(indexHandler, userHandler)
	return appHandler
}

// injector.go:

var wireSet = wire.NewSet(domain.WireSet, datastore.WireSet, usecase.WireSet, controller.WireSet, handler.WireSet)
